config/routes.rb
Rails.application.routes.draw do  
  root "static_pages#home"

  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"

  get "/signup", to: "users#new"

  resources :users, :except => :new  

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :posts do
    resources :comments, :only =>[:create, :destroy]
  end
  get "/search", to: "posts#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = current_user if logged_in?
  end

  def help
    @user = current_user if logged_in?
  end

  def about
    @user = current_user if logged_in?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_navbar.html.erb
<nav class="navbar navbar-default navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/">スタレコ</a>
		</div>
		
		<div class="collapse navbar-collapse" id="navbarEexample1">
			<ul class="nav navbar-nav">
        <% if current_page?(root_path) %>
          <li class="active"><a href="/"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a></li>
          <li><a href="/help"><span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>Help</a></li>
          <li><a href="/about"><span class="glyphicon glyphicon-share-alt" aria-hidden="true"></span>About</a></li>
        <% elsif current_page?(help_path) %>
          <li><a href="/"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a></li>
          <li class="active"><a href="/help"><span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>Help</a></li>
          <li><a href="/about"><span class="glyphicon glyphicon-share-alt" aria-hidden="true"></span>About</a></li>
        <% elsif current_page?(about_path) %>
          <li><a href="/"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a></li>
          <li><a href="/help"><span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>Help</a></li>
          <li class="active"><a href="/about"><span class="glyphicon glyphicon-share-alt" aria-hidden="true"></span>About</a></li>
        <% else %>
          <li><a href="/"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a></li>
          <li><a href="/help"><span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>Help</a></li>
          <li><a href="/about"><span class="glyphicon glyphicon-share-alt" aria-hidden="true"></span>About</a></li>
        <% end %>
			</ul>
      <% if !logged_in? %>
        <p class="navbar-text navbar-right"> <a href="/login" class="navbar-link">ログイン</a> </p>
      <% else %>
        <p class="navbar-text navbar-right"> <%= link_to "ログアウト", "/logout", {method: :delete, class: "navbar-link"} %> </p>
      <% end %>
        <p class="navbar-text"> <a href="/posts/new" class="navbar-link">記事を記録・投稿する</a> </p>
        <div class="search-form">
          <%= form_with url: search_path, method: :get, local: true, class: "navbar-form navbar-left" do |f| %>
            <div class="form-group">
              <%= f.text_field :keyword, value: @keyword, class: "form-control", placeholder: "投稿を検索する" %>
              <%= f.select :category, [["国語", "japanese"], ["数学", "math"], ["理科", "science"], 
                                       ["社会", "social"], ["外国語", "foreign lang"], ["その他", "others"]],
                                        {include_blank: "全て選択"} %>
            </div>
            <%= f.submit "検索" %>
          <% end %>
        </div>
        <p class="navbar-text navbar-right"> <a href="/signup" class="navbar-link">新規登録</a> </p>
      <% if logged_in? %>
        <div class="dropdown navbar-right">
          <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">
            <%= gravatar_for @user, size: 28 %>
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li role="presentation"><a href="/users/<%= @user.id %>">ユーザ・記事情報</a></li>
            <li role="presentation"><a href="/users">ユーザ一覧</a></li>
          </ul>
        </div>
      <% end %>
		</div>
	</div>
</nav>

app/views/static_pages/about.html.erb
<% provide( :title, "About") %>
<!-- navバー -->
<%= render :partial => "navbar" %>

app/views/static_pages/help.html.erb
<% provide( :title, "Help") %>
<!-- navバー -->
<%= render :partial => "navbar" %>

app/views/static_pages/home.html.erb
<% provide( :title, "Home" ) %>
<%= render :partial => "navbar" %>
<div class="jumbotron">
	<h1>スタレコ</h1>
	<p>勉強した内容を共有、閲覧できるサービス</p>
	<p><a class="btn btn-primary btn-lg" href="/signup" role="button">新規登録</a></p>
</div>