config/routes.rb
Rails.application.routes.draw do  
  root "static_pages#home"

  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"

  get "/signup", to: "users#new"

  resources :users, :except => :new  

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :posts do
    resources :comments, :only =>[:create, :destroy]
  end
  get "/search", to: "posts#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  default_scope -> {order(created_at: :desc)}
  validates :user_id, presence: true
  validates :post_id, presence: true
  validates :content, presence: true, length: {maximum: 1000}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController  
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy 

  def create
    @user = current_user
    @post = Post.find_by(id: params[:post_id])
    @comment_create = current_user.comments.build(comment_params)
    @comments = @post.comments.paginate(page: params[:page], per_page: 5)
    if @comment_create.save
      flash[:success] = "コメントしました"
      redirect_to @post
    else
      flash[:danger] = @comment_create.errors.full_messages.join(" ")
      redirect_to @post 
    end
  end

  def destroy
    @comment = Comment.find_by(params[:id])
    @comment.destroy!
    flash[:success] = "削除されました"
    redirect_to Post.find_by(id: params[:post_id])
  end

  private

    def comment_params
      params.require(:comment).permit(:content, :post_id)
    end

    def correct_user
      comment = Comment.find_by(id: params[:id])
      unless has_this_comment?(comment) || current_user.admin?
        flash[:danger] = "正しいユーザではありません"
        redirect_to Post.find_by(id: params[:post_id])
      end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def has_this_comment(comment)
    user = User.find_by(id: comment.user_id)
  end

  def has_this_comment?(comment)
    user = User.find_by(id: comment.user_id)
    current_user == user ? true : false
  end
end

app/views/comments/_comment.html.erb
<li>
  <div class="one-comment">
    <div class="user-info">
      <%= gravatar_for has_this_comment(comment), size: 40 %>
      <%= link_to has_this_comment(comment).name, has_this_comment(comment) %>
    </div>
    <div class="comment-content">
      <span><%= comment.content %></span>
    </div>
    <div class="comment-timestamp">
      <span><%= time_ago_in_words(comment.created_at) %>前にコメント</span>
    <div>
    <div class="delete-link">
    <% if logged_in? %>
      <% if current_user.admin? || @user == has_this_comment(comment) %>
        <span class="comment-destroy"> 
          | <%= link_to "削除", post_comment_path(@post, comment), method: :delete,
                      data: {confirm: "本当に削除しますか？"} %>
        </span>
      <% end %>
    <% end %>
    </div>
  </div>
</li>